### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by pociej** [golemfactory/deposit-payment-example#62]
```[tasklist]
### Tasks
- [x] add both eth and glm balances to web3modal button
- [x] refactor UI according to https://drive.google.com/file/d/13AsrdqgtCQYGZjUMGoBLScaezgmbOxUq/view?usp=sharing
```

**Comment by pociej** [comment]
Events list : 
- Deposit created 
  - transaction id with link to etherscan 
  - amount, fee, validity date 
- Allocation created 
  - amount, validity date 
- Agreement signed 
  - provider 
- Files ok/file not ok 
  - color code 
- new invoice 
  - amount, 
  - if paid when transaction id 
- agreement termination 
- payment on blockchain ( for provider ) 
   - invoice id 
- allocation released 
   - ??? 
- payment for fees ( deposit close ) 
  - transaction id , link to ehterscan

**Comment by golmek** [comment]
Prereq: https://github.com/golemfactory/deposit-payment-example/issues/36

**Comment by golmek** [comment]
New UI for internal clicking to be released tomorrow

**Comment by golmek** [comment]
still not released on: https://deposit.dev.golem.network/ 
ETA: today
